AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for creating a DynamoDB table, Lambda functions, and API Gateway for the To-Do List API.

Resources:
  # DynamoDB Table
  ToDoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ToDoTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true
      Tags:
        - Key: Environment
          Value: Production

  # Lambda Function for Creating ToDo Item
  CreateToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CreateToDoFunction
      CodeUri: src/create_todo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ToDoTable
      Events:
        FunctionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ToDoApi
            Path: /createTodo
            Method: post
      Tags:
        Project: "ToDoList"
  GetToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetToDoFunction
      CodeUri: src/get_todo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          TABLE_NAME: !Ref ToDoTable
      Events:
        FunctionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ToDoApi
            Path: /getTodo
            Method: GET
      Tags:
        Project: "ToDoList"
      Role: !GetAtt LambdaExecutionRole.Arn

  UpdateToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: UpdateToDoFunction
      CodeUri: src/update_todo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ToDoTable
      Events:
        FunctionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ToDoApi
            Path: /updateTodo/{id}
            Method: put
      Tags:
        Project: "ToDoList"
    
  DeleteToDoFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: DeleteToDoFunction
      CodeUri: src/delete_todo/
      Handler: app.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaExecutionRole.Arn
      Environment:
        Variables:
          TABLE_NAME: !Ref ToDoTable
      Events:
        FunctionEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ToDoApi
            Path: /deleteTodo/{id}
            Method: put
      Tags:
        Project: "ToDoList"

  # IAM Role for Lambda Execution (with CloudWatch logs permissions)
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaDynamoDBExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action: "sts:AssumeRole"
            Principal:
              Service: "lambda.amazonaws.com"
      Policies:
        - PolicyName: LambdaDynamoDBPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                  - "dynamodb:Scan"
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/ToDoTable"

              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: "*"

        - PolicyName: LambdaInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action: "lambda:InvokeFunction"
                Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${AWS::StackName}*"

  APIGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: APIGatewayExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: APIGatewayLoggingAndInvokePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub "arn:aws:logs:ap-south-1:${AWS::AccountId}:log-group:/aws/apigateway/*"
              - Effect: "Allow"
                Action:
                  - "dynamodb:PutItem"
                  - "dynamodb:GetItem"
                  - "dynamodb:Scan" 
                  - "dynamodb:UpdateItem"
                  - "dynamodb:DeleteItem"
                Resource: !GetAtt ToDoTable.Arn

  # API Gateway Resource
  ToDoApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/"
          LoggingLevel: ERROR
          DataTraceEnabled: false
          MetricsEnabled: true
      Cors:
        AllowMethods: "GET,POST,PUT,OPTIONS"
        AllowHeaders: "Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token"
        AllowOrigin: "*"
      GatewayResponses:
        UNAUTHORIZED:
          ResponseParameters:
            Headers:
              Access-Control-Allow-Origin: "*"
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "ToDoApi"
          version: "1.0"
        x-amazon-apigateway-request-validators:
          basic:
            validateRequestBody: true
            validateRequestParameters: true
          params-only:
            validateRequestBody: true
            validateRequestParameters: false
        x-amazon-apigateway-request-validator: basic
        paths:
          /createTodo:
            post:
              summary: "Create a new ToDo item"
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/${CreateToDoFunction.Arn}/invocations
                credentials: !GetAtt APIGatewayExecutionRole.Arn 
                httpMethod: post
                type: aws_proxy
              responses:
                "200":
                  description: "Successful response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "204":
                  description: "No content"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "401":
                  description: "Unauthorized"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "500":
                  description: "Server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
          /getTodo:
            get:
              summary: "Fetching all ToDo items"
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetToDoFunction.Arn}/invocations
                credentials: !GetAtt APIGatewayExecutionRole.Arn 
                httpMethod: GET
                type: aws_proxy
              responses:
                "200":
                  description: "Successful response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "204":
                  description: "No content"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "401":
                  description: "Unauthorized"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "500":
                  description: "Server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
          /updateTodo/{id}:
            put:
              summary: "Update an existing ToDo item by ID"
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/${UpdateToDoFunction.Arn}/invocations
                credentials: !GetAtt APIGatewayExecutionRole.Arn 
                httpMethod: put
                type: aws_proxy
              responses:
                "200":
                  description: "Successful response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "204":
                  description: "No content"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "401":
                  description: "Unauthorized"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "500":
                  description: "Server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
          /deleteTodo/{id}:
            delete:
              summary: "Delete an existing ToDo item by ID"
              x-amazon-apigateway-integration:
                uri: !Sub arn:aws:apigateway:ap-south-1:lambda:path/2015-03-31/functions/${DeleteToDoFunction.Arn}/invocations
                credentials: !GetAtt APIGatewayExecutionRole.Arn 
                httpMethod: delete
                type: aws_proxy
              responses:
                "200":
                  description: "Successful response"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "204":
                  description: "No content"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "401":
                  description: "Unauthorized"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string
                "500":
                  description: "Server error"
                  headers:
                    Access-Control-Allow-Origin:
                      type: string 

Outputs:
  ToDoTableName:
    Description: Name of the DynamoDB table
    Value: !Ref ToDoTable
    Export:
      Name: ToDoTableName

  ApiEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ToDoApi}.execute-api.${AWS::Region}.amazonaws.com/prod"